Allow to install the library as a CMake project
F2I-Consulting/fesapi pull request #344
Opened 2024-03-15 08:15 UTC by CharlesGueunet

(Thanks for sending a pull request! Please make sure you click the link above to view the contribution guidelines, then fill out the blanks below.)

What does this implement/fix? Explain your changes.
---------------------------------------------------

These changes add the cmake mechanism to install the project so it can be used in a find_package by other projects.

Any relevant logs, error output, etc?
-------------------------------------
There is one change in this MR which is just commenting some lines causing a linker error on recent clang compilers.  The error is provided in comment

Where has this been tested?
---------------------------
**Operating System:** Gentoo Linux

I also used fespp to ensure this library is correctly installed.

Other comments:
---------------

This PR is related to another MR updating fespp to uses this library as expected (will be provided here when available).

2024-03-15 10:42 UTC, philippeVerney commented
Thanks a lot @CharlesGueunet 
I try to look at it deeper next week and wil let you know.

2024-03-15 11:03 UTC, philippeVerney commented
@CharlesGueunet Would it be possible to target the dev master instead of the master one?

2024-03-15 12:28 UTC, CharlesGueunet commented
> @CharlesGueunet Would it be possible to target the dev branch instead of the master one?

Done 

> I try to look at it deeper next week and wil let you know.

Thank you

2024-03-20 17:16 UTC, philippeVerney requested changes
Thanks for all this work.
Not sure to have enough CMAKE knowledge to deeply understand the proposed changes but hopefully my review should be a bit useful.
I have a commit to push/patch right after this review.

2024-03-20 17:29 UTC, philippeVerney commented
Here is a patch trying to resolve my comments above.
[0001-Proposal-after-review.patch](https://github.com/F2I-Consulting/fesapi/files/14670410/0001-Proposal-after-review.patch)

I also rebased on origin/dev to check and it is fine.

2024-03-22 10:22 UTC, CharlesGueunet commented on src/FesapiCppConfig.cmake.in
I have slightly updated your changes so the .in is in the cmake directory, but the generated file stay in the build dir only (and not in the source).

2024-03-22 16:55 UTC, merged